#!/usr/bin/env bash

WALLDIR="$HOME/Pictures/wallpapers"

IMG=$(
    fd -e jpg -e png -e webp -e jxl . "$WALLDIR" |
        sk --prompt="🖼 wallpaper > "
)

[ -z "$IMG" ] && exit 0

hyprctl hyprpaper preload "$IMG" >/dev/null
hyprctl hyprpaper wallpaper ",$IMG" >/dev/null
