name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Check formatting
        run: nix build .#checks.x86_64-linux.format --print-build-logs
